spring.application.name=taskboard

spring.profiles.default=dev

spring.data.web.pageable.max-page-size=100

server.servlet.session.persistent=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=60

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
